
package gov.nih.nlm.ncbi.soap.eutils;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "eFetchTaxonService", targetNamespace = "http://www.ncbi.nlm.nih.gov/soap/eutils/", wsdlLocation = "http://eutils.ncbi.nlm.nih.gov/soap/v2.0/efetch_taxon.wsdl")
public class EFetchTaxonService
    extends Service
{

    private final static URL EFETCHTAXONSERVICE_WSDL_LOCATION;
    private final static WebServiceException EFETCHTAXONSERVICE_EXCEPTION;
    private final static QName EFETCHTAXONSERVICE_QNAME = new QName("http://www.ncbi.nlm.nih.gov/soap/eutils/", "eFetchTaxonService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://eutils.ncbi.nlm.nih.gov/soap/v2.0/efetch_taxon.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EFETCHTAXONSERVICE_WSDL_LOCATION = url;
        EFETCHTAXONSERVICE_EXCEPTION = e;
    }

    public EFetchTaxonService() {
        super(__getWsdlLocation(), EFETCHTAXONSERVICE_QNAME);
    }

    public EFetchTaxonService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EFETCHTAXONSERVICE_QNAME, features);
    }

    public EFetchTaxonService(URL wsdlLocation) {
        super(wsdlLocation, EFETCHTAXONSERVICE_QNAME);
    }

    public EFetchTaxonService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EFETCHTAXONSERVICE_QNAME, features);
    }

    public EFetchTaxonService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EFetchTaxonService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EUtilsServiceSoap
     */
    @WebEndpoint(name = "eUtilsServiceSoap")
    public EUtilsServiceSoap getEUtilsServiceSoap() {
        return super.getPort(new QName("http://www.ncbi.nlm.nih.gov/soap/eutils/", "eUtilsServiceSoap"), EUtilsServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EUtilsServiceSoap
     */
    @WebEndpoint(name = "eUtilsServiceSoap")
    public EUtilsServiceSoap getEUtilsServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ncbi.nlm.nih.gov/soap/eutils/", "eUtilsServiceSoap"), EUtilsServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EFETCHTAXONSERVICE_EXCEPTION!= null) {
            throw EFETCHTAXONSERVICE_EXCEPTION;
        }
        return EFETCHTAXONSERVICE_WSDL_LOCATION;
    }

}
