
package gov.nih.nlm.ncbi.soap.eutils;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import gov.nih.nlm.ncbi.soap.eutils.efetch_taxonomy.EFetchRequest;
import gov.nih.nlm.ncbi.soap.eutils.efetch_taxonomy.EFetchResult;
import gov.nih.nlm.ncbi.soap.eutils.efetch_taxonomy.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "eUtilsServiceSoap", targetNamespace = "http://www.ncbi.nlm.nih.gov/soap/eutils/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EUtilsServiceSoap {


    /**
     * 
     * @param inpp
     * @return
     *     returns gov.nih.nlm.ncbi.soap.eutils.efetch_taxonomy.EFetchResult
     */
    @WebMethod(operationName = "run_eFetch", action = "efetch")
    @WebResult(name = "eFetchResult", targetNamespace = "http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_taxonomy", partName = "outp")
    public EFetchResult runEFetch(
        @WebParam(name = "eFetchRequest", targetNamespace = "http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_taxonomy", partName = "inpp")
        EFetchRequest inpp);

}
