//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 01:52:02 PM BST 
//


package org.BioLayoutExpress3D.Files.webservice.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.BioLayoutExpress3D.Files.webservice.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Help_QNAME = new QName("", "help");
    private final static QName _SearchResponse_QNAME = new QName("", "searchResponse");
    private final static QName _TraverseResponse_QNAME = new QName("", "traverseResponse");
    private final static QName _ErrorResponse_QNAME = new QName("", "errorResponse");
    private final static QName _DataResponse_QNAME = new QName("", "dataResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.BioLayoutExpress3D.Files.webservice.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Help }
     * 
     */
    public Help createHelp() {
        return new Help();
    }

    /**
     * Create an instance of {@link SearchResponse }
     * 
     */
    public SearchResponse createSearchResponse() {
        return new SearchResponse();
    }

    /**
     * Create an instance of {@link TraverseResponse }
     * 
     */
    public TraverseResponse createTraverseResponse() {
        return new TraverseResponse();
    }

    /**
     * Create an instance of {@link ErrorResponse }
     * 
     */
    public ErrorResponse createErrorResponse() {
        return new ErrorResponse();
    }

    /**
     * Create an instance of {@link DataResponse }
     * 
     */
    public DataResponse createDataResponse() {
        return new DataResponse();
    }

    /**
     * Create an instance of {@link TraverseEntry }
     * 
     */
    public TraverseEntry createTraverseEntry() {
        return new TraverseEntry();
    }

    /**
     * Create an instance of {@link SearchHit }
     * 
     */
    public SearchHit createSearchHit() {
        return new SearchHit();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Help }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "help")
    public JAXBElement<Help> createHelp(Help value) {
        return new JAXBElement<Help>(_Help_QNAME, Help.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "searchResponse")
    public JAXBElement<SearchResponse> createSearchResponse(SearchResponse value) {
        return new JAXBElement<SearchResponse>(_SearchResponse_QNAME, SearchResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TraverseResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "traverseResponse")
    public JAXBElement<TraverseResponse> createTraverseResponse(TraverseResponse value) {
        return new JAXBElement<TraverseResponse>(_TraverseResponse_QNAME, TraverseResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErrorResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "errorResponse")
    public JAXBElement<ErrorResponse> createErrorResponse(ErrorResponse value) {
        return new JAXBElement<ErrorResponse>(_ErrorResponse_QNAME, ErrorResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dataResponse")
    public JAXBElement<DataResponse> createDataResponse(DataResponse value) {
        return new JAXBElement<DataResponse>(_DataResponse_QNAME, DataResponse.class, null, value);
    }

}
