//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 01:52:02 PM BST 
//


package org.BioLayoutExpress3D.Files.webservice.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{}ServiceResponse">
 *       &lt;sequence>
 *         &lt;element name="searchHit" type="{}SearchHit" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="numHits" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="maxHitsPerPage" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="pageNo" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchResponse", propOrder = {
    "searchHit"
})
public class SearchResponse
    extends ServiceResponse
{

    @XmlElement(nillable = true)
    protected List<SearchHit> searchHit;
    @XmlAttribute(name = "numHits")
    protected Integer numHits;
    @XmlAttribute(name = "maxHitsPerPage")
    protected Integer maxHitsPerPage;
    @XmlAttribute(name = "pageNo")
    protected Integer pageNo;
    @XmlAttribute(name = "comment")
    protected String comment;

    /**
     * Gets the value of the searchHit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the searchHit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSearchHit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SearchHit }
     * 
     * 
     */
    public List<SearchHit> getSearchHit() {
        if (searchHit == null) {
            searchHit = new ArrayList<SearchHit>();
        }
        return this.searchHit;
    }

    /**
     * Gets the value of the numHits property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumHits() {
        return numHits;
    }

    /**
     * Sets the value of the numHits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumHits(Integer value) {
        this.numHits = value;
    }

    /**
     * Gets the value of the maxHitsPerPage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxHitsPerPage() {
        return maxHitsPerPage;
    }

    /**
     * Sets the value of the maxHitsPerPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxHitsPerPage(Integer value) {
        this.maxHitsPerPage = value;
    }

    /**
     * Gets the value of the pageNo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPageNo() {
        return pageNo;
    }

    /**
     * Sets the value of the pageNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPageNo(Integer value) {
        this.pageNo = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

}
